# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog's
owner: eggoez
email: eg@goez.my.id
description: > # this means to ignore newlines until "baseurl:"
  Everything will be changed!
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://eggoezz.github.io" # the base hostname & protocol for your site
permalink: /:categories/:title.html
twitter_username: eggoez
github_username:  eggoez

# Build settings
markdown: kramdown
